oceanbase-ce:
  tag: obadvanced
  servers:
    # Please don't use hostname, only IP can be supported
    - name: test
      ip: 127.0.0.1 # 修改为合适的IP地址

  global:
    home_path: /home/wsh/ob-advanced # 这⾥指定⾃⼰机器上⼀个可⽤的磁盘⽬录
    # Please set devname as the network adaptor's name whose ip is in the setting of severs.
    # if set severs as "127.0.0.1", please set devname as "lo"
    # if current ip is 192.168.1.10, and the ip's network adaptor's name is "eth0", please use "eth0"
    devname: lo # 修改为合适的⽹卡
    mysql_port: 2881
    rpc_port: 2882
    zone: zone1
    cluster_id: 1
    # please set memory limit to a suitable value which is matching resource.
    memory_limit: 8G
    datafile_size: 30G # 限制数据⽂件⼤⼩
